unit_test:
  image: composer:latest
  stage: test
  script:
    - composer update
    - composer install
    - cp .env.example .env
    - php artisan key:generate
    - vendor/bin/phpunit
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml